version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: heroku
    versions:
    - 7.47.11
    - 7.47.12
    - 7.47.13
    - 7.48.0
    - 7.49.0
    - 7.49.1
    - 7.50.0
    - 7.51.0
    - 7.52.0
  - dependency-name: ejs
    versions:
    - 3.1.5
